name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: viniciusFernandesInacio
          svg_out_path: output/github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
